name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 6 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          close-issue-message: 'This issue was closed because it has been stale for 14 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          close-pr-message: 'This PR was closed because it has been stale for 14 days with no activity.'
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: never-stale
          exempt-pr-labels: never-stale
          any-of-labels: information-requested
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 14
          stale-issue-message: 'This package does not have an assigned owner and is considered unmaintained. As such this package is in feature-freeze and this issue will be closed with 14 days unless a new owner or a sponsor (@open-telemetry/javascript-approvers) for the feature is found. It is the responsibility of the author to find a sponsor for this component.'
          close-issue-message: 'This issue was closed because no owner or sponsor has been found after 14 days'
          only-labels: pkg-status:unmaintained,feature-request
          exempt-issue-labels: bug,has:sponsor
      - uses: actions/stale@v9
        with:
          days-before-pr-stale: 0
          days-before-pr-close: 14
          stale-pr-message: 'This package does not have an assigned owner and is considered unmaintained. As such this package is in feature-freeze and this PR will be closed with 14 days unless a new owner or a sponsor (@open-telemetry/javascript-approvers) for the feature is found. It is the responsibility of the author to find a sponsor for this component.'
          close-pr-message: 'This issue was closed because no owner or sponsor has been found after 14 days'
          only-labels: pkg-status:unmaintained
          exempt-pr-labels: bug,has:sponsor
