name: TAV for PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  parse-labels:
    runs-on: ubuntu-latest
    container:
      image: node:20
    env:
      PR_LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
    outputs:
      args: ${{ steps.npm-workspace-args.outputs.args }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parse labels into npm workspace arguments
        id: npm-workspace-args
        run: |
          OUTPUT=`node scripts/pr-labels-to-npm-workspace-args.mjs "$PR_LABELS"`
          echo "args=$OUTPUT" >> $GITHUB_OUTPUT

  tav:
    uses: ./.github/workflows/test-all-versions.yml
    needs: parse-labels
    with:
      npm-workspace-args: ${{ needs.parse-labels.outputs.args }}
    if: ${{ needs.parse-labels.outputs.args != '' }}
