name: Unit Tests via npm cache & CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-test-cache:
    strategy:
      fail-fast: false
      matrix:
        node: ["8", "10", "12", "14", "16"]
        include:
          - node: "8"
            lerna-extra-args: >-
              --ignore @opentelemetry/instrumentation-aws-sdk
              --ignore @opentelemetry/instrumentation-pino
          - node: "10"
            lerna-extra-args: >-
              --ignore @opentelemetry/instrumentation-pino
    runs-on: ubuntu-latest
    # services:
    #   memcached:
    #     image: memcached:1.6.9-alpine
    #     ports:
    #     - 11211:11211
    #   mongo:
    #     image: mongo
    #     ports:
    #     - 27017:27017
    #   mysql:
    #     image: circleci/mysql:5.7
    #     env:
    #       MYSQL_USER: otel
    #       MYSQL_PASSWORD: secret
    #       MYSQL_DATABASE: circle_database
    #       MYSQL_ROOT_PASSWORD: rootpw
    #     ports:
    #     - 3306:3306
    #     options: >-
    #       --health-cmd="mysqladmin ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #   postgres:
    #     image: circleci/postgres:9.6-alpine
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_DB: circle_database
    #     ports:
    #     - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #   redis:
    #     image: redis
    #     ports:
    #     - 6379:6379
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #   cassandra:
    #     image: bitnami/cassandra:3
    #     ports:
    #     - 9042:9042
    env:
      RUN_CASSANDRA_TESTS: 1
      RUN_MEMCACHED_TESTS: 1
      RUN_MONGODB_TESTS: 1
      RUN_MYSQL_TESTS: 1
      RUN_POSTGRES_TESTS: 1
      RUN_REDIS_TESTS: 1
      OPENTELEMETRY_MEMCACHED_HOST: localhost
      OPENTELEMETRY_MEMCACHED_PORT: 11211
      POSTGRES_USER: postgres
      POSTGRES_DB: circle_database
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      OPENTELEMETRY_REDIS_HOST: localhost
      OPENTELEMETRY_REDIS_PORT: 6379
      MONGODB_DB: opentelemetry-tests
      MONGODB_HOST: localhost
      MONGODB_PORT: 27017
      MYSQL_USER: otel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: circle_database
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      NPM_CONFIG_UNSAFE_PERM: true
      CASSANDRA_HOST: localhost
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache Dependencies
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Legacy Peer Dependencies for npm 7
        if: matrix.node == '16'
        run: npm config set legacy-peer-deps=true
      - name: Install Root Dependencies
        run: npm install --ignore-scripts
      - name: Bootstrap Dependencies
        run: npx lerna bootstrap --hoist --nohoist='zone.js' --nohoist='mocha' --nohoist='ts-mocha'
      # Don't actually run tests for now
      # - name: Unit tests
      #   run: npm run test:ci:changed -- ${{ matrix.lerna-extra-args }}
      # - name: Report Coverage
      #   if: matrix.node == '14'
      #   run: npm run codecov:ci:changed
  browser-tests-cache:
    runs-on: ubuntu-latest
    container:
      image: circleci/node:12-browsers
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Permission Setup
        run: sudo chmod -R 777 /github /__w
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache Dependencies
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Root Dependencies
        run: npm install --ignore-scripts
      - name: Bootstrap Dependencies
        run: npx lerna bootstrap
      # Don't actually run tests for now
      # - name: Unit tests
      #   run: npm run test:browser
      # - name: Report Coverage
      #   run: npm run codecov:browser
